[tool.poetry]
name = "mlnode-load-balancer"
version = "0.1.0"
description = "Lightweight load balancer in front of MLNode instances"
readme = "README.md"
authors = [
    "Gonka AI"
]
packages = [{include = "load_balancer", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = ">=0.115.8"
httpx = ">=0.27.0"
uvicorn = ">=0.34.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-asyncio = "^0.23"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
