services:
  proxy:
    container_name: ${KEY_NAME}-proxy
    image: ghcr.io/product-science/proxy:latest
    build:
      context: ../proxy
      dockerfile: Dockerfile
    ports:
      - "${PROXY_PORT:-80}:80"  # Configurable external port, defaults to 80
      - "${API_SSL_PORT:-443}:443"  # Optional external SSL port
    environment:
      # Configure backend service ports via environment variables
      - KEY_NAME=${KEY_NAME}
      - PROXY_ADD_NODE_PREFIX=true
      - GONKA_API_PORT=${GONKA_API_PORT:-9000}
      - CHAIN_RPC_PORT=${CHAIN_RPC_PORT:-26657}
      - CHAIN_API_PORT=${CHAIN_API_PORT:-1317}
      - CHAIN_GRPC_PORT=${CHAIN_GRPC_PORT:-9090}
      # DASHBOARD_PORT is only set when explorer is included (no default value)
      - DASHBOARD_PORT=${DASHBOARD_PORT}
    depends_on:
      - chain-node
      - api
    networks:
      - chain-public
    restart: unless-stopped